### ISSUE TITLE
putting flag into buffer instead of sample data?

### ISSUE THREAD

**Issue by pat-rogers** [tomek-o/scream-stm32f429#1]
In on_scream_server_recv() there is the code that inserts the remaining sample value into the buffer:

    if (remaining_sample) {
        if (jbuf_put(remaining_sample) == 0) {
            remaining_sample = false;

but  it seems to me that it should be putting the sample value instead:

    if (remaining_sample) {
        if (jbuf_put(remaining_sample_value) == 0) {
            remaining_sample = false;

What do you think?  Of course, I may have missed something, I'm not familiar with the code but it looked odd.

**Comment by tomek-o** [comment]
You are definitely right, thanks.
This mechanism is intended to prevent left <-> right channel swapping in case of uneven number of samples being pushed into FIFO.

**Comment by pat-rogers** [comment]
You're very welcome!
